matrix:
  include:
    - language: java
      sudo: false
      before_install:
        - openssl aes-256-cbc -K $encrypted_261f0aee381c_key -iv $encrypted_261f0aee381c_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
        - gcloud auth activate-service-account --key-file client-secret.json
      script:
        - gcloud config set project oceanic-trees-254104
        - cd restful-web-services
        - mvn clean install
        - mvn test
        - if [ $TRAVIS_BRANCH = "deploy" ]; mvn appengine:deploy; fi

    - language: node_js
      node_js:
        - 12
      sudo: false
      before_install:
        - openssl aes-256-cbc -K $encrypted_261f0aee381c_key -iv $encrypted_261f0aee381c_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
        - gcloud auth activate-service-account --key-file client-secret.json
        - gcloud config set app/use_deprecated_preparation True
      script:
        - gcloud config set project oceanic-trees-254104
        - cd frontend/todo-app
        - npm clean-install
        - CI=false npm run build
        - if [ "TRAVIS_BRANCH = "deploy" ]; gcloud -q app deploy; fi
      skip_files:
        - ^node_modules/.*$ 
